"""create diagnostic runs and issues

Revision ID: 1a69c7554b89
Revises: 465d32473e31
Create Date: 2026-07-28 12:57:15.125730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a69c7554b89'
down_revision = '465d32473e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostic_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_version_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_errors', sa.Integer(), nullable=False),
    sa.Column('total_warnings', sa.Integer(), nullable=False),
    sa.Column('total_infos', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('RUNNING', 'COMPLETED', 'FAILED')", name='ck_diagnostic_runs_status'),
    sa.ForeignKeyConstraint(['schedule_version_id'], ['schedule_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnostic_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnostic_runs_schedule_version_id'), ['schedule_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnostic_runs_status'), ['status'], unique=False)

    op.create_table('diagnostic_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagnostic_run_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assignment_date', sa.Date(), nullable=True),
    sa.Column('military_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('is_blocking', sa.Boolean(), nullable=False),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category in ('CONFIGURATION', 'MILITARY', 'TEAM', 'CYCLE', 'UNAVAILABILITY', 'RESTRICTION', 'ASSIGNMENT', 'SCHEDULE_STATE', 'COVERAGE', 'REST', 'COMPENSATION', 'SYSTEM')", name='ck_diagnostic_issues_category'),
    sa.CheckConstraint("level in ('ERROR', 'WARNING', 'INFO')", name='ck_diagnostic_issues_level'),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['diagnostic_run_id'], ['diagnostic_runs.id'], ),
    sa.ForeignKeyConstraint(['military_id'], ['militaries.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnostic_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnostic_issues_assignment_date'), ['assignment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnostic_issues_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnostic_issues_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnostic_issues_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnostic_issues_diagnostic_run_id'), ['diagnostic_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnostic_issues_is_blocking'), ['is_blocking'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnostic_issues_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnostic_issues_military_id'), ['military_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnostic_issues_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostic_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnostic_issues_team_id'))
        batch_op.drop_index(batch_op.f('ix_diagnostic_issues_military_id'))
        batch_op.drop_index(batch_op.f('ix_diagnostic_issues_level'))
        batch_op.drop_index(batch_op.f('ix_diagnostic_issues_is_blocking'))
        batch_op.drop_index(batch_op.f('ix_diagnostic_issues_diagnostic_run_id'))
        batch_op.drop_index(batch_op.f('ix_diagnostic_issues_code'))
        batch_op.drop_index(batch_op.f('ix_diagnostic_issues_category'))
        batch_op.drop_index(batch_op.f('ix_diagnostic_issues_assignment_id'))
        batch_op.drop_index(batch_op.f('ix_diagnostic_issues_assignment_date'))

    op.drop_table('diagnostic_issues')
    with op.batch_alter_table('diagnostic_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnostic_runs_status'))
        batch_op.drop_index(batch_op.f('ix_diagnostic_runs_schedule_version_id'))

    op.drop_table('diagnostic_runs')
    # ### end Alembic commands ###
