"""create militaries table

Revision ID: 2ac4ce2a1e70
Revises: 
Create Date: 2026-07-27 15:38:25.214109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ac4ce2a1e70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('militaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('nim', sa.String(length=30), nullable=False),
    sa.Column('functional_type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('militaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_militaries_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_militaries_functional_type'), ['functional_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_militaries_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_militaries_nim'), ['nim'], unique=True)
        batch_op.create_index(batch_op.f('ix_militaries_start_date'), ['start_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('militaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_militaries_start_date'))
        batch_op.drop_index(batch_op.f('ix_militaries_nim'))
        batch_op.drop_index(batch_op.f('ix_militaries_is_active'))
        batch_op.drop_index(batch_op.f('ix_militaries_functional_type'))
        batch_op.drop_index(batch_op.f('ix_militaries_end_date'))

    op.drop_table('militaries')
    # ### end Alembic commands ###
