"""add complete military data fields

Revision ID: 3d500fe2d57a
Revises: a78b8ff4bc33
Create Date: 2026-07-28 23:01:18.568222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d500fe2d57a'
down_revision = 'a78b8ff4bc33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('militaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=90), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_paid_service_volunteer', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.create_index(batch_op.f('ix_militaries_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_militaries_last_name'), ['last_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('militaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_militaries_last_name'))
        batch_op.drop_index(batch_op.f('ix_militaries_first_name'))
        batch_op.drop_column('is_paid_service_volunteer')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
