"""create assignments and assignment changes

Revision ID: 465d32473e31
Revises: 91f6d17e963f
Create Date: 2026-07-28 12:39:17.391503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465d32473e31'
down_revision = '91f6d17e963f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_version_id', sa.Integer(), nullable=False),
    sa.Column('military_id', sa.Integer(), nullable=False),
    sa.Column('assignment_date', sa.Date(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('has_override', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_cleared', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source in ('MANUAL', 'SYSTEM', 'IMPORTED')", name='ck_assignments_source'),
    sa.CheckConstraint('(is_cleared = 1 and code is null) or (is_cleared = 0 and code is not null)', name='ck_assignments_cleared_code'),
    sa.CheckConstraint("code is null or code in ('AT1', 'AT2', 'AT3', 'PO1', 'PO2', 'PO3', 'PT', 'P', 'R', 'CR', 'FC', 'FF', 'DS', 'DC', 'LF', 'LP', 'BM', 'LC', 'LN', 'DIL', 'TRIB', 'INQ', 'DCP', 'D24', 'FORMACAO', 'TIRO', 'OUTRA')", name='ck_assignments_code'),
    sa.CheckConstraint('code is null or length(code) between 1 and 30', name='ck_assignments_code_length'),
    sa.ForeignKeyConstraint(['military_id'], ['militaries.id'], ),
    sa.ForeignKeyConstraint(['schedule_version_id'], ['schedule_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_version_id', 'military_id', 'assignment_date', name='uq_assignments_version_military_date')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignments_assignment_date'), ['assignment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_has_override'), ['has_override'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_is_cleared'), ['is_cleared'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_is_locked'), ['is_locked'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_is_manual'), ['is_manual'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_military_id'), ['military_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_schedule_version_id'), ['schedule_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_source'), ['source'], unique=False)

    op.create_table('assignment_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=40), nullable=False),
    sa.Column('previous_code', sa.String(length=30), nullable=True),
    sa.Column('new_code', sa.String(length=30), nullable=True),
    sa.Column('previous_locked', sa.Boolean(), nullable=True),
    sa.Column('new_locked', sa.Boolean(), nullable=True),
    sa.Column('previous_override', sa.Boolean(), nullable=True),
    sa.Column('new_override', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("change_type in ('CREATED', 'UPDATED', 'CLEARED', 'LOCKED', 'UNLOCKED', 'OVERRIDE_APPLIED', 'OVERRIDE_REMOVED')", name='ck_assignment_changes_type'),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignment_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_changes_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_changes_change_type'), ['change_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_changes_change_type'))
        batch_op.drop_index(batch_op.f('ix_assignment_changes_assignment_id'))

    op.drop_table('assignment_changes')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_source'))
        batch_op.drop_index(batch_op.f('ix_assignments_schedule_version_id'))
        batch_op.drop_index(batch_op.f('ix_assignments_military_id'))
        batch_op.drop_index(batch_op.f('ix_assignments_is_manual'))
        batch_op.drop_index(batch_op.f('ix_assignments_is_locked'))
        batch_op.drop_index(batch_op.f('ix_assignments_is_cleared'))
        batch_op.drop_index(batch_op.f('ix_assignments_has_override'))
        batch_op.drop_index(batch_op.f('ix_assignments_code'))
        batch_op.drop_index(batch_op.f('ix_assignments_assignment_date'))

    op.drop_table('assignments')
    # ### end Alembic commands ###
