"""create team cycle references

Revision ID: 6706124b423b
Revises: 6a09479ecf71
Create Date: 2026-07-27 16:45:39.436345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6706124b423b'
down_revision = '6a09479ecf71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_cycle_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.Column('reference_phase', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('reference_phase between 1 and 6', name='ck_team_cycle_references_phase'),
    sa.CheckConstraint('valid_until is null or valid_until >= valid_from', name='ck_team_cycle_references_valid_period'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'valid_from', name='uq_team_cycle_references_team_valid_from')
    )
    with op.batch_alter_table('team_cycle_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_cycle_references_reference_date'), ['reference_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_cycle_references_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_cycle_references_valid_from'), ['valid_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_cycle_references_valid_until'), ['valid_until'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_cycle_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_cycle_references_valid_until'))
        batch_op.drop_index(batch_op.f('ix_team_cycle_references_valid_from'))
        batch_op.drop_index(batch_op.f('ix_team_cycle_references_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_cycle_references_reference_date'))

    op.drop_table('team_cycle_references')
    # ### end Alembic commands ###
