"""create military restrictions

Revision ID: 671d9ca0bf61
Revises: 6706124b423b
Create Date: 2026-07-27 17:14:06.650832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671d9ca0bf61'
down_revision = '6706124b423b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('military_restrictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('military_id', sa.Integer(), nullable=False),
    sa.Column('restriction_type', sa.String(length=40), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('monday', sa.Boolean(), nullable=False),
    sa.Column('tuesday', sa.Boolean(), nullable=False),
    sa.Column('wednesday', sa.Boolean(), nullable=False),
    sa.Column('thursday', sa.Boolean(), nullable=False),
    sa.Column('friday', sa.Boolean(), nullable=False),
    sa.Column('saturday', sa.Boolean(), nullable=False),
    sa.Column('sunday', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("restriction_type in ('UNAVAILABLE', 'AVAILABLE_ONLY', 'SPECIAL_AVAILABILITY')", name='ck_military_restrictions_type'),
    sa.CheckConstraint('(start_time is null and end_time is null) or (start_time is not null and end_time is not null)', name='ck_military_restrictions_time_pair'),
    sa.CheckConstraint('end_date is null or end_date >= start_date', name='ck_military_restrictions_date_period'),
    sa.ForeignKeyConstraint(['military_id'], ['militaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('military_restrictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_military_restrictions_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_military_restrictions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_military_restrictions_military_id'), ['military_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_military_restrictions_restriction_type'), ['restriction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_military_restrictions_start_date'), ['start_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('military_restrictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_military_restrictions_start_date'))
        batch_op.drop_index(batch_op.f('ix_military_restrictions_restriction_type'))
        batch_op.drop_index(batch_op.f('ix_military_restrictions_military_id'))
        batch_op.drop_index(batch_op.f('ix_military_restrictions_is_active'))
        batch_op.drop_index(batch_op.f('ix_military_restrictions_end_date'))

    op.drop_table('military_restrictions')
    # ### end Alembic commands ###
