"""create teams and memberships

Revision ID: 6a09479ecf71
Revises: 2ac4ce2a1e70
Create Date: 2026-07-27 15:59:04.664079

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a09479ecf71'
down_revision = '2ac4ce2a1e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=1), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("code in ('A', 'B', 'C', 'D', 'E')", name='ck_teams_official_code'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_teams_is_active'), ['is_active'], unique=False)

    teams_table = sa.table(
        'teams',
        sa.column('code', sa.String),
        sa.column('name', sa.String),
        sa.column('is_active', sa.Boolean),
        sa.column('created_at', sa.DateTime),
        sa.column('updated_at', sa.DateTime),
    )
    timestamp = datetime(2026, 7, 27, 0, 0, 0)
    op.bulk_insert(
        teams_table,
        [
            {
                'code': code,
                'name': f'Equipa {code}',
                'is_active': True,
                'created_at': timestamp,
                'updated_at': timestamp,
            }
            for code in ('A', 'B', 'C', 'D', 'E')
        ],
    )

    op.create_table('military_team_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('military_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['military_id'], ['militaries.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('military_team_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_military_team_history_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_military_team_history_military_id'), ['military_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_military_team_history_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_military_team_history_team_id'), ['team_id'], unique=False)
        batch_op.create_index(
            'uq_military_team_history_current_military',
            ['military_id'],
            unique=True,
            sqlite_where=sa.text('end_date IS NULL'),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('military_team_history', schema=None) as batch_op:
        batch_op.drop_index('uq_military_team_history_current_military')
        batch_op.drop_index(batch_op.f('ix_military_team_history_team_id'))
        batch_op.drop_index(batch_op.f('ix_military_team_history_start_date'))
        batch_op.drop_index(batch_op.f('ix_military_team_history_military_id'))
        batch_op.drop_index(batch_op.f('ix_military_team_history_end_date'))

    op.drop_table('military_team_history')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_is_active'))
        batch_op.drop_index(batch_op.f('ix_teams_code'))

    op.drop_table('teams')
    # ### end Alembic commands ###
