"""create schedule months and versions

Revision ID: 91f6d17e963f
Revises: b67e7ed6d0f7
Create Date: 2026-07-28 12:00:57.440343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91f6d17e963f'
down_revision = 'b67e7ed6d0f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_months',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('NOT_GENERATED', 'DRAFT', 'VALIDATED', 'PUBLISHED', 'CLOSED')", name='ck_schedule_months_status'),
    sa.CheckConstraint('month between 1 and 12', name='ck_schedule_months_month'),
    sa.CheckConstraint('year between 2000 and 2100', name='ck_schedule_months_year'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_schedule_months_year_month')
    )
    with op.batch_alter_table('schedule_months', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_months_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_months_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_months_year'), ['year'], unique=False)

    op.create_table('schedule_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_month_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source in ('INITIAL', 'MANUAL', 'SYSTEM')", name='ck_schedule_versions_source'),
    sa.CheckConstraint("status in ('NOT_GENERATED', 'DRAFT', 'VALIDATED', 'PUBLISHED', 'CLOSED')", name='ck_schedule_versions_status'),
    sa.CheckConstraint('version_number >= 1', name='ck_schedule_versions_number'),
    sa.ForeignKeyConstraint(['schedule_month_id'], ['schedule_months.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_month_id', 'version_number', name='uq_schedule_versions_month_number')
    )
    with op.batch_alter_table('schedule_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_versions_schedule_month_id'), ['schedule_month_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_versions_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_versions_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_versions_status'))
        batch_op.drop_index(batch_op.f('ix_schedule_versions_source'))
        batch_op.drop_index(batch_op.f('ix_schedule_versions_schedule_month_id'))

    op.drop_table('schedule_versions')
    with op.batch_alter_table('schedule_months', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_months_year'))
        batch_op.drop_index(batch_op.f('ix_schedule_months_status'))
        batch_op.drop_index(batch_op.f('ix_schedule_months_month'))

    op.drop_table('schedule_months')
    # ### end Alembic commands ###
