"""create generation runs and selection details

Revision ID: a284728b2308
Revises: 1a69c7554b89
Create Date: 2026-07-28 13:21:26.416573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a284728b2308'
down_revision = '1a69c7554b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_version_id', sa.Integer(), nullable=False),
    sa.Column('diagnostic_run_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_created', sa.Integer(), nullable=False),
    sa.Column('total_preserved_manual', sa.Integer(), nullable=False),
    sa.Column('total_unfilled', sa.Integer(), nullable=False),
    sa.Column('total_warnings', sa.Integer(), nullable=False),
    sa.Column('parameters_json', sa.Text(), nullable=True),
    sa.Column('summary_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('RUNNING', 'COMPLETED', 'COMPLETED_WITH_WARNINGS', 'FAILED')", name='ck_generation_runs_status'),
    sa.ForeignKeyConstraint(['diagnostic_run_id'], ['diagnostic_runs.id'], ),
    sa.ForeignKeyConstraint(['schedule_version_id'], ['schedule_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_runs_diagnostic_run_id'), ['diagnostic_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_runs_schedule_version_id'), ['schedule_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_runs_status'), ['status'], unique=False)

    op.create_table('assignment_selection_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generation_run_id', sa.Integer(), nullable=False),
    sa.Column('assignment_date', sa.Date(), nullable=False),
    sa.Column('service_code', sa.String(length=30), nullable=False),
    sa.Column('military_id', sa.Integer(), nullable=True),
    sa.Column('is_eligible', sa.Boolean(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("service_code in ('AT1', 'AT2', 'AT3', 'PO1', 'PO2', 'PO3')", name='ck_assignment_selection_details_service_code'),
    sa.ForeignKeyConstraint(['generation_run_id'], ['generation_runs.id'], ),
    sa.ForeignKeyConstraint(['military_id'], ['militaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignment_selection_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_selection_details_assignment_date'), ['assignment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_selection_details_generation_run_id'), ['generation_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_selection_details_is_eligible'), ['is_eligible'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_selection_details_is_selected'), ['is_selected'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_selection_details_military_id'), ['military_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_selection_details_service_code'), ['service_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_selection_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_selection_details_service_code'))
        batch_op.drop_index(batch_op.f('ix_assignment_selection_details_military_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_selection_details_is_selected'))
        batch_op.drop_index(batch_op.f('ix_assignment_selection_details_is_eligible'))
        batch_op.drop_index(batch_op.f('ix_assignment_selection_details_generation_run_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_selection_details_assignment_date'))

    op.drop_table('assignment_selection_details')
    with op.batch_alter_table('generation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_runs_status'))
        batch_op.drop_index(batch_op.f('ix_generation_runs_schedule_version_id'))
        batch_op.drop_index(batch_op.f('ix_generation_runs_diagnostic_run_id'))

    op.drop_table('generation_runs')
    # ### end Alembic commands ###
