"""add operational testing support v1.9

Revision ID: a78b8ff4bc33
Revises: 9a4e2b7c1d60
Create Date: 2026-07-28 22:07:50.466128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78b8ff4bc33'
down_revision = '9a4e2b7c1d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operational_test_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_version_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('manual_changes_count', sa.Integer(), nullable=False),
    sa.Column('coverage_missing_count', sa.Integer(), nullable=False),
    sa.Column('blocking_errors_count', sa.Integer(), nullable=False),
    sa.Column('warnings_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision in ('REJECTED', 'ACCEPTABLE_WITH_CHANGES', 'APPROVED_REFERENCE')", name='ck_operational_test_evaluations_decision'),
    sa.ForeignKeyConstraint(['schedule_version_id'], ['schedule_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_version_id', name='uq_operational_test_evaluations_version')
    )
    with op.batch_alter_table('operational_test_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operational_test_evaluations_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_operational_test_evaluations_schedule_version_id'), ['schedule_version_id'], unique=False)

    op.create_table('operational_test_evaluation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('previous_decision', sa.String(length=40), nullable=True),
    sa.Column('new_decision', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("new_decision in ('REJECTED', 'ACCEPTABLE_WITH_CHANGES', 'APPROVED_REFERENCE')", name='ck_operational_test_evaluation_events_new'),
    sa.CheckConstraint("previous_decision is null or previous_decision in ('REJECTED', 'ACCEPTABLE_WITH_CHANGES', 'APPROVED_REFERENCE')", name='ck_operational_test_evaluation_events_previous'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['operational_test_evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operational_test_evaluation_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operational_test_evaluation_events_evaluation_id'), ['evaluation_id'], unique=False)

    with op.batch_alter_table('schedule_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_operational_test', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('test_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('test_created_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('archive_reason', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_schedule_versions_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_versions_is_operational_test'), ['is_operational_test'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_versions_is_operational_test'))
        batch_op.drop_index(batch_op.f('ix_schedule_versions_is_archived'))
        batch_op.drop_column('archive_reason')
        batch_op.drop_column('archived_at')
        batch_op.drop_column('is_archived')
        batch_op.drop_column('test_created_at')
        batch_op.drop_column('test_notes')
        batch_op.drop_column('is_operational_test')

    with op.batch_alter_table('operational_test_evaluation_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operational_test_evaluation_events_evaluation_id'))

    op.drop_table('operational_test_evaluation_events')
    with op.batch_alter_table('operational_test_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operational_test_evaluations_schedule_version_id'))
        batch_op.drop_index(batch_op.f('ix_operational_test_evaluations_decision'))

    op.drop_table('operational_test_evaluations')
    # ### end Alembic commands ###
