"""add safe regeneration metadata

Revision ID: a999dc4dceba
Revises: a284728b2308
Create Date: 2026-07-28 13:52:26.455887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a999dc4dceba'
down_revision = 'a284728b2308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_version_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('result_version_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('generation_mode', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_generation_runs_generation_mode'), ['generation_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_runs_result_version_id'), ['result_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_runs_source_version_id'), ['source_version_id'], unique=False)
        batch_op.create_check_constraint('ck_generation_runs_generation_mode', "generation_mode is null or generation_mode in ('FILL_EMPTY', 'REGENERATE_AUTOMATIC')")
        batch_op.create_foreign_key('fk_generation_runs_result_version_id_schedule_versions', 'schedule_versions', ['result_version_id'], ['id'])
        batch_op.create_foreign_key('fk_generation_runs_source_version_id_schedule_versions', 'schedule_versions', ['source_version_id'], ['id'])

    with op.batch_alter_table('schedule_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_version_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('generation_mode', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_schedule_versions_generation_mode'), ['generation_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_versions_parent_version_id'), ['parent_version_id'], unique=False)
        batch_op.create_check_constraint('ck_schedule_versions_generation_mode', "generation_mode is null or generation_mode in ('FILL_EMPTY', 'REGENERATE_AUTOMATIC')")
        batch_op.create_foreign_key('fk_schedule_versions_parent_version_id_schedule_versions', 'schedule_versions', ['parent_version_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_versions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_schedule_versions_parent_version_id_schedule_versions', type_='foreignkey')
        batch_op.drop_constraint('ck_schedule_versions_generation_mode', type_='check')
        batch_op.drop_index(batch_op.f('ix_schedule_versions_parent_version_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_versions_generation_mode'))
        batch_op.drop_column('generation_mode')
        batch_op.drop_column('parent_version_id')

    with op.batch_alter_table('generation_runs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_generation_runs_source_version_id_schedule_versions', type_='foreignkey')
        batch_op.drop_constraint('fk_generation_runs_result_version_id_schedule_versions', type_='foreignkey')
        batch_op.drop_constraint('ck_generation_runs_generation_mode', type_='check')
        batch_op.drop_index(batch_op.f('ix_generation_runs_source_version_id'))
        batch_op.drop_index(batch_op.f('ix_generation_runs_result_version_id'))
        batch_op.drop_index(batch_op.f('ix_generation_runs_generation_mode'))
        batch_op.drop_column('generation_mode')
        batch_op.drop_column('result_version_id')
        batch_op.drop_column('source_version_id')

    # ### end Alembic commands ###
