"""create unavailabilities

Revision ID: b67e7ed6d0f7
Revises: 671d9ca0bf61
Create Date: 2026-07-28 09:16:41.997098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b67e7ed6d0f7'
down_revision = '671d9ca0bf61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unavailabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('military_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('is_full_day', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('location', sa.String(length=250), nullable=True),
    sa.Column('travel_minutes_before', sa.Integer(), nullable=False),
    sa.Column('travel_minutes_after', sa.Integer(), nullable=False),
    sa.Column('compensation_status', sa.String(length=40), nullable=False),
    sa.Column('compensation_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("code in ('LF', 'LP', 'BM', 'LC', 'LN', 'DIL', 'TRIB', 'INQ', 'FORMACAO', 'TIRO', 'OUTRA')", name='ck_unavailabilities_code'),
    sa.CheckConstraint("compensation_status in ('NOT_APPLICABLE', 'PENDING_DECISION', 'GENERATES_CREDIT', 'DOES_NOT_GENERATE_CREDIT')", name='ck_unavailabilities_compensation_status'),
    sa.CheckConstraint("status in ('PLANNED', 'CONFIRMED', 'CANCELLED')", name='ck_unavailabilities_status'),
    sa.CheckConstraint('(is_full_day = 1 and start_time is null and end_time is null) or (is_full_day = 0 and start_time is not null and end_time is not null)', name='ck_unavailabilities_time_semantics'),
    sa.CheckConstraint('end_date >= start_date', name='ck_unavailabilities_date_period'),
    sa.CheckConstraint('travel_minutes_before >= 0 and travel_minutes_after >= 0', name='ck_unavailabilities_travel_non_negative'),
    sa.ForeignKeyConstraint(['military_id'], ['militaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unavailabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unavailabilities_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_unavailabilities_compensation_status'), ['compensation_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_unavailabilities_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_unavailabilities_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_unavailabilities_military_id'), ['military_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unavailabilities_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_unavailabilities_status'), ['status'], unique=False)

    op.create_table('unavailability_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unavailability_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('previous_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("event_type in ('CREATED', 'UPDATED', 'CONFIRMED', 'CANCELLED', 'REACTIVATED')", name='ck_unavailability_events_type'),
    sa.ForeignKeyConstraint(['unavailability_id'], ['unavailabilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unavailability_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unavailability_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_unavailability_events_unavailability_id'), ['unavailability_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unavailability_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unavailability_events_unavailability_id'))
        batch_op.drop_index(batch_op.f('ix_unavailability_events_event_type'))

    op.drop_table('unavailability_events')
    with op.batch_alter_table('unavailabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unavailabilities_status'))
        batch_op.drop_index(batch_op.f('ix_unavailabilities_start_date'))
        batch_op.drop_index(batch_op.f('ix_unavailabilities_military_id'))
        batch_op.drop_index(batch_op.f('ix_unavailabilities_is_active'))
        batch_op.drop_index(batch_op.f('ix_unavailabilities_end_date'))
        batch_op.drop_index(batch_op.f('ix_unavailabilities_compensation_status'))
        batch_op.drop_index(batch_op.f('ix_unavailabilities_code'))

    op.drop_table('unavailabilities')
    # ### end Alembic commands ###
